name: Deploy LINE webhook to Cloud Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          audience: https://github.com/makokoid-eng/akarilab
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 470.0.0'
          export_default_credentials: true

      - name: Deploy Cloud Functions v2 (line-webhook)
        working-directory: cloud/functions/line-webhook
        run: |
          gcloud functions deploy line-webhook \
            --gen2 \
            --region="${{ secrets.GCP_REGION }}" \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --runtime=nodejs20 \
            --entry-point=app \
            --source=. \
            --trigger-http \
            --allow-unauthenticated \
            --set-env-vars "LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }},LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"

