name: Deploy LINE webhook to Cloud Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'cloud/functions/line-webhook/**'
      - '.github/workflows/line-webhook-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REGION: ${{ vars.GCP_REGION }}
      FUNCTION_NAME: ${{ vars.GCP_LINE_FUNCTION_NAME }}
      RUNTIME_SA: ${{ vars.GCP_RUNTIME_SA }}
      LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate to Google Cloud (JSON key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        # Auth method switched to JSON key for personal project (no organization)

      - name: gcloud init
        run: |
          set -euo pipefail
          gcloud config set project "${PROJECT_ID}"
          gcloud config set functions/region "${REGION}"
          gcloud --version

      - name: "Preflight: check service account"
        run: |
          set -euo pipefail
          echo "PROJECT_ID=${PROJECT_ID}"
          echo "RUNTIME_SA=${RUNTIME_SA}"
          gcloud iam service-accounts describe "${RUNTIME_SA}" \
            --format="value(email)" >/dev/null
          echo "✔ Service Account exists"

      - name: Install dependencies (function)
        working-directory: cloud/functions/line-webhook
        run: |
          set -euo pipefail
          echo "[ls] cloud/functions/line-webhook"
          ls -la
          if [ -f package-lock.json ]; then
            echo "[npm] lockfile found → npm ci"
            npm ci
          else
            echo "[npm] lockfile NOT found → npm install"
            npm install
          fi

      - name: Deploy Cloud Functions v2 (line-webhook)
        working-directory: cloud/functions/line-webhook
        run: |
          set -euo pipefail
          gcloud functions deploy "${FUNCTION_NAME}" \
            --gen2 \
            --runtime=nodejs20 \
            --region="${REGION}" \
            --entry-point=app \
            --trigger-http \
            --allow-unauthenticated \
            --service-account="${RUNTIME_SA}" \
            --set-env-vars="LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET},LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN},OPENAI_API_KEY=${OPENAI_API_KEY}"

      - name: Show function URL
        run: |
          URL=$(gcloud functions describe "${FUNCTION_NAME}" --region="${REGION}" --format="value(serviceConfig.uri)")
          echo "FUNCTION_URL=${URL}"
          echo "FUNCTION_URL=${URL}" >> $GITHUB_OUTPUT
